<a href="https://colab.research.google.com/github/dork-nerd/BASIC_daily_expense/blob/master/Numpyprac.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np       #array of same type are faster than lists in python
a = np.array([1,2,3,4])  #initialization of an array
b = np.array((1,2,3,4),dtype="f")  #can be instialized like this too
print(a)
print(type(a))
print(b.dtype)           #gives the data type of the elements
print(a.dtype)
print(a.ndim)            #gives the dimension of the array(1-D array)
c = np.array([[5,6],[7,8]])  #intialization of an 2-D array
print(c[0,1])
print(c.shape)           #tells the order of the array
print(c.size)            #tells the no of all elements
d = np.arange(10)        #gives an array from intial point to end point-1
print(d)
e = np.random.permutation(np.arange(10))  #np.random.permutation() - shuffles the array
print(e)
f = np.random.randint(20,30)
print(f)
g = c.reshape(4,1)     #reshapes into having 4 rows and 1 column
print(g)

#array[start:stop:jump]

h = c[0:2,0:1]         #array slicing .. first 2 rows and 1st column .. and any changes to h reflects in main array also
i = c[0:1,0:2].copy()  #array slicing .. 1st row and first 2 columns .. and saves a copy of it in var i
print(h)
print(i)
j = np.arange(10)       #array of 10 elements (0 to 9)
print(j)
idx = np.argwhere(j==9) #searches where ever 9 is there and stores that index in a 2d array
print(idx)              #2-D array consisting all the indexes where elemnet is 9
j[idx[0,0]] = 10
print(j)
print(g.T)              #prints the transpose of the array

#import numpy.linalg as la (library for linear algebra)

print(j[[1,2,3]])       #prints the array of index with 1 2 3 (gives copy unlike slicing)
print(j[j<5])           #prints the numbers less than 5       (gives copy unlike slicing)
print(j[[True,False,True,True,False,True,True,False,True,False]])    #(same above)

[1 2 3 4]
<class 'numpy.ndarray'>
float32
int64
1
6
(2, 2)
4
[0 1 2 3 4 5 6 7 8 9]
[1 8 9 4 0 3 5 2 7 6]
29
[[5]
 [6]
 [7]
 [8]]
[[5]
 [7]]
[[5 6]]
[0 1 2 3 4 5 6 7 8 9]
[[9]]
[ 0  1  2  3  4  5  6  7  8 10]
[[5 6 7 8]]
[1 2 3]
[0 1 2 3 4]
[0 2 3 5 6 8]
